src/PersonalThesaurus/Controllers/ContextTermController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PersonalThesaurus.Data;
using PersonalThesaurus.Models;

namespace PersonalThesaurus.Controllers
{
    public class ContextTermController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContextTermController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: ContextTerm
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ContextTerm.Include(c => c.Vocabulary);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ContextTerm/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contextTerm = await _context.ContextTerm.SingleOrDefaultAsync(m => m.ID == id);
            if (contextTerm == null)
            {
                return NotFound();
            }

            return View(contextTerm);
        }

        // GET: ContextTerm/Create
        public IActionResult Create()
        {
            ViewData["VocabularyID"] = new SelectList(_context.Vocabulary, "ID", "ID");

           

            return View();
        }

        // POST: ContextTerm/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,VocabularyID,term,type")] ContextTerm contextTerm)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contextTerm);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["VocabularyID"] = new SelectList(_context.Vocabulary, "ID", "ID", contextTerm.VocabularyID);
          
            return View(contextTerm);
        }

        // GET: ContextTerm/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

           
            //change next

            var contextTerm = await _context.ContextTerm.SingleOrDefaultAsync(m => m.ID == id);
            

            if (contextTerm == null)
            {
                return NotFound();
            }
            //ViewData["VocabularyID"] = new SelectList(_context.Vocabulary, "ID", "ID", contextTerm.VocabularyID);
           
            ViewData["VocabularyID"] = new SelectList(_context.Vocabulary, "ID", "ID", contextTerm.Vocabulary);
            var vocabview = new Vocabulary();

            return View(contextTerm);
        }

        // POST: ContextTerm/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,VocabularyID,term,type")] ContextTerm contextTerm)
        {
            if (id != contextTerm.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contextTerm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContextTermExists(contextTerm.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["VocabularyID"] = new SelectList(_context.Vocabulary, "ID", "ID", contextTerm.VocabularyID);
            
            return View(contextTerm);
        }

        // GET: ContextTerm/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contextTerm = await _context.ContextTerm.SingleOrDefaultAsync(m => m.ID == id);
            if (contextTerm == null)
            {
                return NotFound();
            }

            return View(contextTerm);
        }

        // POST: ContextTerm/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contextTerm = await _context.ContextTerm.SingleOrDefaultAsync(m => m.ID == id);
            _context.ContextTerm.Remove(contextTerm);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ContextTermExists(int id)
        {
            return _context.ContextTerm.Any(e => e.ID == id);
        }
    }
}

src/PersonalThesaurus/Controllers/VocabularyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PersonalThesaurus.Data;
using PersonalThesaurus.Models;

namespace PersonalThesaurus.Controllers
{
    public class VocabularyController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VocabularyController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Vocabulary
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vocabulary.ToListAsync());
        }

        // GET: Vocabulary/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            if (vocabulary == null)
            {
                return NotFound();
            }

            return View(vocabulary);
        }

        // GET: Vocabulary/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vocabulary/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,term")] Vocabulary vocabulary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vocabulary);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(vocabulary);
        }

        // GET: Vocabulary/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            if (vocabulary == null)
            {
                return NotFound();
            }
            return View(vocabulary);
        }

        // POST: Vocabulary/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,term")] Vocabulary vocabulary)
        {
            if (id != vocabulary.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vocabulary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VocabularyExists(vocabulary.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(vocabulary);
        }

        // GET: Vocabulary/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            if (vocabulary == null)
            {
                return NotFound();
            }

            return View(vocabulary);
        }

        // POST: Vocabulary/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            _context.Vocabulary.Remove(vocabulary);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool VocabularyExists(int id)
        {
            return _context.Vocabulary.Any(e => e.ID == id);
        }
    }
}

src/PersonalThesaurus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Personal Thesaurus</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/freelancer.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Personal Thesaurus</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Vocabulary" asp-action="Index">Add</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="ContextTerm" asp-action="Index">Context Terms</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Progress</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - PersonalThesaurus</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>