src/PersonalThesaurus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PersonalThesaurus.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/PersonalThesaurus/Controllers/VocabularyViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PersonalThesaurus.Data;
using PersonalThesaurus.Models;

namespace PersonalThesaurus.Controllers
{
    public class VocabularyViewController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VocabularyViewController(ApplicationDbContext context)
        {
            _context = context;    
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<Vocabulary> vocab = new List<Vocabulary>();
            using (_context)
            {
                vocab = _context.Vocabulary.Include(p => p.contextTerms).ToList();
            }
            return View("Index", vocab);
        }

        // GET: VocabularyView
        //public async Task<IActionResult> Index()
        //{


        //    var applicationDbContext = _context.Vocabulary.Include(v => v.image);





        //    return View(await applicationDbContext.ToListAsync());
        //}

        // GET: VocabularyView/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            if (vocabulary == null)
            {
                return NotFound();
            }

            return View(vocabulary);
        }

        // GET: VocabularyView/Create
        public IActionResult Create()
        {
            ViewData["imageID"] = new SelectList(_context.Image, "ID", "ID");

           
            return View();
        }

        // POST: VocabularyView/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,imageID,term")] Vocabulary vocabulary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vocabulary);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["imageID"] = new SelectList(_context.Image, "ID", "ID", vocabulary.imageID);

            
            return View(vocabulary);
        }

        // GET: VocabularyView/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            if (vocabulary == null)
            {
                return NotFound();
            }
            ViewData["imageID"] = new SelectList(_context.Image, "ID", "ID", vocabulary.imageID);
            return View(vocabulary);
        }

        // POST: VocabularyView/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,imageID,term")] Vocabulary vocabulary)
        {
            if (id != vocabulary.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vocabulary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VocabularyExists(vocabulary.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["imageID"] = new SelectList(_context.Image, "ID", "ID", vocabulary.imageID);
            return View(vocabulary);
        }

        // GET: VocabularyView/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            if (vocabulary == null)
            {
                return NotFound();
            }

            return View(vocabulary);
        }

        // POST: VocabularyView/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vocabulary = await _context.Vocabulary.SingleOrDefaultAsync(m => m.ID == id);
            _context.Vocabulary.Remove(vocabulary);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool VocabularyExists(int id)
        {
            return _context.Vocabulary.Any(e => e.ID == id);
        }
    }
}

src/PersonalThesaurus/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/PersonalThesaurus/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/PersonalThesaurus/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
.glyphicon{
    font-size:4em;

}

</style>

<div class="row text-center">
    <h1 style="font-size:4em;">Personal Thesaurus</h1><hr />
    <p class="text-muted">Build your vocabulary</p>
    <a asp-action="index" asp-controller="VocabularyView" class="btn btn-primary btn-lg">
        Check out your personal thesaurus.
    </a>
</div>
<div class="container-fluid">
    <section id="About">
        <div class="row">
            <div class="col-xs-16 col-sm-8 col-md-4 text-center">
                <span class="glyphicon glyphicon-book text-primary"></span>
                <h3>Add New Words</h3>
                <p class="text-muted">Found a word in a book you are reading - Add it!</p>
            </div>
        
       
            <div class="col-xs-16 col-sm-8 col-md-4 text-center">
                <span class="glyphicon glyphicon-edit text-primary"></span>
                <h3>Edit your Thesaurus</h3>
                <p class="text-muted">Add a synonym or picture!</p>
            </div>
        
            <div class="col-xs-16 col-sm-8 col-md-4 text-center">
                <span class="glyphicon glyphicon-education text-primary"></span>
                <h3>Check your Progress</h3>
                <p class="text-muted">How are you doing? Find out here!</p>
            </div>
        </div>
    </section>
</div>